FROM python:3.11

WORKDIR /app

# Add code and install codebase
COPY requirements.txt requirements.txt
COPY . .

# Install libs
RUN pip3 install -r requirements.txt
RUN pip3 install -e .

# Expose ports (or do this in docker-compose)
EXPOSE ${STREAMLIT_PORT}

# Specify default command
CMD streamlit run streamlit_app.py --server.port=${STREAMLIT_PORT} --server.address=0.0.0.0
