# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving
    ports:
      - "8080:8080/tcp"
      - "8080:8080/udp"
    environment:
      COMET_API_KEY: ${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
##  streamlit:
##    build:
##      context: ./
##      dockerfile: ./Dockerfile.streamlit
##      args:
##        ARG: <ARG>
##    image: ift6758/streamlit:<TAG>
##    ports:
##      - <STREAMLIT_PORT>:<STREAMLIT_PORT>
##    environment:
##      OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      

     
