# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: nhlanalysis/serving
    ports:
      - "8080:8080"
    environment:
      COMET_API_KEY: ${COMET_API_KEY}
      SERVING_PORT: 8080
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: nhlanalysis/streamlit
    ports:
      - "8081:8081"
    environment:
      SERVING_IP: "serving"
      SERVING_PORT: 8080
      STREAMLIT_PORT: 8081
