name: nhlanalysis-conda-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - opencv
  - tqdm
  - lxml
  - plotly
  - setuptools
  - ipykernel
  - ipywidgets
  - jupyterlab>=3.0.0
  - ipdb